import type { AppStoreState } from '../types/store';

export const initialState: AppStoreState = {
  entities: [],
  relations: [],
  entityMap: {},
  entityPhysics: {},
  relationPropagation: {},
  scenarios: [],
  predictions: [],
  zoneMap: {},
  zoneLabels: { A: '', B: '', C: '', D: '', E: '', F: '' },
  liveIds: [],
  floorConfig: null,
  view: 'floor',
  positions: {},
  pinnedIds: new Set(),
  tempIds: new Set(),
  visibleIds: new Set(),
  focusId: null,
  focusNeighborhood: new Set(),
  focusEdgeIds: new Set(),
  simulatedTime: null,
  activeScenario: 'unchanged',
  dark: false,
  kairosOpen: false,
  kairosEntityId: null,
  pinnedCharts: [],
  onboardingOpen: false,
  pendingMachines: [],
  offlineIds: new Set(),
  actionLog: [],
  spatialWidgets: [],
  signalTimestamps: {},
};
