import type { AppStoreState } from '../types/store';

export const initialState: AppStoreState = {
  entities: [],
  relations: [],
  entityMap: {},
  entityPhysics: {},
  relationPropagation: {},
  simulation: {
    scenarios: [],
    predictions: [],
    simulatedTime: null,
    activeScenario: 'unchanged',
  },
  plant: {
    liveIds: [],
    offlineIds: new Set(),
    signalTimestamps: {},
    reportBindings: {
      oee: { entityId: '', source: 'physics', field: 'currentOee', fallback: 0 },
      speed: { entityId: '', source: 'physics', field: 'currentValue', fallback: 0 },
      tension: { entityId: '', source: 'physics', field: 'currentValue', fallback: 0 },
    },
  },
  zoneMap: {},
  zoneLabels: { A: '', B: '', C: '', D: '', E: '', F: '' },
  floorConfig: null,
  graphConfig: null,
  view: 'floor',
  positions: {},
  pinnedIds: new Set(),
  tempIds: new Set(),
  visibleIds: new Set(),
  focusId: null,
  focusNeighborhood: new Set(),
  focusEdgeIds: new Set(),
  dark: false,
  kairosOpen: false,
  kairosEntityId: null,
  pinnedCharts: [],
  onboardingOpen: false,
  pendingMachines: [],
  actionLog: [],
  spatialWidgets: [],
};
